### PR TITLE
remove io/ioutil

### PR DESCRIPTION
**Pull request by mpldr**
Since ioutil has been deprecated, replace the calls to ioutil with the functions that are now called anyways.

### CODE REVIEW

**Comment by pelletier** [comment]
Thank you for taking the time to make this change! I'm not keen on removing those deprecated imports yet, see https://github.com/pelletier/go-toml/issues/898#issuecomment-1716315155. Essentially I think changing those imports will be worth it either in case of a new major version of go-toml, or when Go actually removes them, whichever comes first.

**Comment by mpldr** [comment]
Ironically, this is now done in #911 anyways :D

**Comment by pelletier** [comment]
I have no problem updating the imports in the program that generates tests :)

**Comment by mpldr** [comment]
I mean, only one of them was in an imported package anyways. The rest was in tests or main packages.

**Pull request closed without merging**
