### PR TITLE
Golangci lint

### PR DESCRIPTION
**Pull request by pelletier**
Follow up to https://github.com/pelletier/go-toml/pull/474 to create the github action.

### CODE REVIEW

**Comment by pelletier** [comment]
@vincentserpoul I like [the integration](https://github.com/pelletier/go-toml/actions/runs/543157054).

Took a look at the reported issues. They seem reasonable to me. If you'd like feel free to to take a stab at them -- for now I'd rather keep focusing on v2.

**Comment by vincentserpoul** [comment]
sounds good. So I'll continue via this PR then and close my previous one?

**Comment by pelletier** [comment]
> Don't you want to actually bring that on the v2 first?

I was thinking we could do both.

> So I'll continue via this PR then and close my previous one?

My suggested flow would be to rebase your branch against this one and fix the issues the linter flagged, then I'll just merge your branch and close this. That's assuming github actions don't need to be merged first to execute on a PR not coming from the repo itself.

**Comment by jidicula** [comment]
@pelletier Would it be ok if I took a crack at some of these lint issues? I can pick up all the low-hanging `ineffectual assignment` errors in a PR, and then you can cherrypick the commits into this or @vincentserpoul's branch.

**Comment by vincentserpoul** [comment]
actually, @jidicula , I have started locally but not commited nor pushed  yet. Let me rebase and commit this today so we can start from there.
Then we can maybe choose which lint we each fix?

**Comment by jidicula** [comment]
> actually, @jidicula , I have started locally but not commited nor pushed yet. Let me rebase and commit this today so we can start from there.
> Then we can maybe choose which lint we each fix?

@vincentserpoul sure, sounds good 🙂

**Comment by pelletier** [comment]
Happy to take any patch that improves code quality! Just want to point out that I'm fully focused on go-toml v2, with no plan to support v1 once it is out. In that light, I think implementing and fixing golangci-lint would probably be more useful on the `v2-wip` branch than on `master` (also, a lot less code there, so probably less issues to deal with, and if it is inserted in the CI process early I think it will be easier to keep up with it).  Still, completely up to you, thank you for helping go-toml!

**Comment by vincentserpoul** [comment]
I created a [PR WIP for v1](https://github.com/pelletier/go-toml/pull/491)
@pelletier it was actually my initial thinking, so I can't agree more :).
I'll create another PR for the v2, so jidicula and I can work in parallel.

**Comment by vincentserpoul** [comment]
just created a [PR WIP for v2](https://github.com/pelletier/go-toml/pull/492)
@jidicula let's split files, it'll be easier. You can work on benchmarks to start with? I'll start with the files in the root

**Comment by jidicula** [comment]
> just created a [PR WIP for v2](https://github.com/pelletier/go-toml/pull/492)
> @jidicula let's split files, it'll be easier. You can work on internal to start with? I'll start with the files in the root

Sounds good!

**Pull request closed without merging**
