### PR TITLE
Add discrete LICENSE file

### PR DESCRIPTION
**Pull request by moorereason**
Identify the license as the MIT License.  Update README to match.

### CODE REVIEW

**Comment by pelletier** [comment]
Merged with https://github.com/pelletier/go-toml/commit/e6271032cc22caac34aa22a8c6ccf272710c85d5

**Comment by pelletier** [comment]
@moorereason out of curiosity, what's the reason for this change?

**Comment by moorereason** [comment]
It's good practice, and the first place I look (LICENSE).  Also, it makes [GoReportCard happier](https://goreportcard.com/report/github.com/pelletier/go-toml), which I was considering adding a badge later if you were up for it.

**Comment by pelletier** [comment]
Cool. Feel free to submit a PR for the GoReportCard badge.

**Pull request closed without merging**
