### PR TITLE
V2 wip golangci lint

### PR DESCRIPTION
**Pull request by vincentserpoul**
multiple things here for errors.go and errors_test.go:
* add spaces between lines, is it ok for you? Not 100% sure the linter setting is working as expected
* enabling // tests
* hacking the last test case so it doesn't fail despite trimming of trailing spaces (do you want me to create an issue for this one?)
* refactored: wrapDecodeError and linesOfContext to have easier linting

### CODE REVIEW

**Comment by pelletier** [comment]
Refactoring looks good. Newlines are a bit much for my personal taste but fore the sake of uniformity I'm fine with it. However I'm not keen on merging this until we have a way to make the linter happy with the literal strings for the test cases.

**Comment by vincentserpoul** [comment]
then, the blank line error needs to be fixed. I thought I saw someone trying to fix it the other day, but it seems to have disappeared, am I right?
Do you have an idea how to fix it or should i go at it?

**Comment by vincentserpoul** [comment]
ok, modified a bit wrapError so it doesnt generate trailing spaces

**Comment by pelletier** [comment]
@vincentserpoul sorry for the late reply. The change looks good. Would you like me to merge?

**Comment by vincentserpoul** [comment]
yes, please!

**Pull request merged**
