### PR TITLE
feat(tomll): add multiLineArray flag to linter

### PR DESCRIPTION
**Pull request by rasta-rocket**
Hi :wave:

First of all, thanks for your work on this project :muscle:.

We use the linter in our CI and thanks to that we have been able to keep the quality of our TOML files.

Since things started to get serious, we have moore and more bigger arrays that became hard to maintain since the linter keep the arrays in one line.

### Explanation of what this pull request does.

The goal of this PR is to add a flag to the linter that allow us to render the TOML file with multulines array (meaning one line by element)

Don't hesitate if you need more details

Cheers :wink:

### CODE REVIEW

**Comment by pelletier** [comment]
Thank you! it does seem useful.

**Comment by rasta-rocket** [comment]
Thanks for the quick review @pelletier :tada:

Question : would it be possible to you to make a new release with that ?

Cheers :wink:

**Comment by pelletier** [comment]
Done! https://github.com/pelletier/go-toml/releases/tag/v1.9.4

**Comment by rasta-rocket** [comment]
@pelletier Sorry me again 😅 : the binaries are missing in the release, are you able to provide them ?

Thanks 🙏

**Comment by pelletier** [comment]
🤦🏻‍♂️ I apologize, looks like the release pipeline is broken. I've manually added the binaries.

**Pull request merged**
