### PR TITLE
Add Parse Type of Time.Duration Friendly, Fix Some Error Message(This is my first pull request ^_^)

### PR DESCRIPTION
**Pull request by Ainiroad**
**Issue:** add link to pelletier/go-toml issue here

Explanation of what this pull request does.

More detailed description of the decisions being made and the reasons why (if the patch is non-trivial).

### CODE REVIEW

**Comment by Ainiroad** [comment]
Ainiroad
Add Parse Type of Time.Duration Friendly

**Comment by Ainiroad** [comment]
Ainiroad
Add Parse Type of Time.Duration Friendly,

**Comment by pelletier** [comment]
Hello! Thanks for your PR :) I don't see a duration type in the TOML spec. Do you mind elaborating on the feature?

**Comment by Ainiroad** [comment]
Thanks for your response :). Time.Duration is not in the TOML spec. But it's a common configuration types in golang. Consider the ease of use of this library, I add this feature.

**Comment by pelletier** [comment]
I like the idea of the feature.

One thing I am concerned about is: when using `Load*(...)`, the current implementation would always create `Time.Duration` objects when parsing a string with the right formatting.  There would be no way to enable/disable that feature, which would create confusion if you don't know about it, or would be annoying to deal with if you do in fact want strings that look like "15m".

What I would be happy with, is to make it an opt-in flag on the `Encoder` and `Decoder`, and only un/marshal with this logic fields that are of type `time.Duration`.

Does that make sense?

**Comment by pelletier** [comment]
Closing because https://github.com/pelletier/go-toml/pull/248 has been merged.

**Pull request closed without merging**
