### PR TITLE
Add continuous fuzzing integration via Fuzzit

### PR DESCRIPTION
**Pull request by yevgenypats**
Hi @pelletier This is the PR as discussed in https://github.com/pelletier/go-toml/issues/287

It adds the following:

* Runs fuzzing continuously on master
* Runs regression with the generated corpus from the above step on every PR.

Cheers,
Yevgeny

### CODE REVIEW

**Comment by yevgenypats** [comment]
@pelletier all checks passes. This is ready for review:)

**Comment by pelletier** [comment]
@yevgenypats Thanks for setting that up! Before merging, I'd like to understand a few things:

1. How do we transfer ownership of the fuzzit account used for testing go-toml to me?
2. What are the steps anyone can use to run the fuzzing script locally?
3. Where are the results of the fuzzing displayed? Alternatively, how am I getting notified that fuzzing on master found new errors? Ideally fuzzit.dev would create a new issue on this repo, but I'm open to most workflows :)

**Comment by yevgenypats** [comment]
@pelletier 
Good questions
1) Please sign up at https://app.fuzzit.dev and I'll add you to the go-toml organization
2) I'll add this to the README as part of the PR.
3) You will get notified via email, an integration with github is something our our roadamp:)

**Comment by pelletier** [comment]
Sounds good. I have signed up (using my github login).

**Comment by yevgenypats** [comment]
done
https://app.fuzzit.dev/orgs/go-toml/dashboard.

You won't see any fuzzing jobs currently running as it will run once it will be merged with master.
The regression is run locally in the CI.

**Comment by pelletier** [comment]
@yevgenypats thanks! Just missing the README steps. Happy to merge now if you'd rather do it in a follow up PR.

**Comment by yevgenypats** [comment]
@pelletier Thanks for pinging me (forgot about this, it was a hectic day in a good way:)). Yes let's do it in a follow-up PR please.

**Comment by pelletier** [comment]
@yevgenypats well, that broke the build :)

https://travis-ci.com/pelletier/go-toml/jobs/226445347

```
$ ./fuzzit.sh
+'[' -z true ']'
+export GO111MODULE=off
+GO111MODULE=off
+go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build
+TARGET=toml-fuzzer
+go-fuzz-build -libfuzzer -o toml-fuzzer.a github.com/pelletier/go-toml
+clang -fsanitize=fuzzer toml-fuzzer.a -o toml-fuzzer
+wget -q -O fuzzit https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.23/fuzzit_Linux_x86_64
+chmod a+x fuzzit
+'[' false == false ']'
+TYPE=fuzzing
+./fuzzit create job --type fuzzing go-toml/toml-fuzzer toml-fuzzer
2019/08/19 19:58:32 Creating job...
2019/08/19 19:58:32 Please set env variable FUZZIT_API_KEY or pass --api-key. API Key for you account: https://app.fuzzit.dev/settings
The command "./fuzzit.sh" exited with 1.
```

**Comment by yevgenypats** [comment]
strange. looking into this right now.

**Comment by pelletier** [comment]
Manually added the API key to the Travis settings. Seems to work now.

**Comment by yevgenypats** [comment]
ok cool. I guess the secret secure either was wrong or needs it's not exported and maybe `global` directive is needed. Thanks:)

**Comment by yevgenypats** [comment]
the fuzzing job runs successfully!
http://localhost:3000/orgs/go-toml/targets/toml-fuzzer/lkCFdE756xUH4a1K2Jj1

**Comment by pelletier** [comment]
From the [Travis doc](https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables):

> Encryption and decryption keys are tied to the repository. If you fork a project and add it to Travis CI, it will not have access to the encrypted variables

I think that was the culprit.

**Comment by pelletier** [comment]
Awesome!

**Pull request merged**
