### PR TITLE
fix #279 add possibility to handle anonymous structs

### LINKED ISSUE #279: Unexpected behavior of decoding to nested anonym struct
**Describe the bug**
I tried to extend some struct to parse full toml-file and return just part of it.

**To Reproduce**
```toml
some = "value X"
another = "value Y"
```

```go
type A struct {
	Some string `toml:"some"`
}

type B struct {
	A
	Another string `toml:"another"`
}

var b B
toml.NewDecoder(r).Decode(&cnf)
fmt.Println(b)
```

**Expected behavior**
```
{{value X} value Y}
```
For example the `encoding/json` behavior: https://play.golang.org/p/x8kaSVpuqh3

**Versions**
 - go-toml: v1.3.0
 - go: 1.11.5
 - operating system: macOS

**Additional context**
Where it's happening: https://github.com/kamilsk/lift/blob/2a8adcf60311d217be784f172699d83a2031f48d/internal/config/app.go#L69-L77
TOML file: https://github.com/kamilsk/lift/blob/2a8adcf60311d217be784f172699d83a2031f48d/testdata/app.toml

### PR DESCRIPTION
**Pull request by kamilsk**
**Issue:** #279 

Handle anonymous struct. Add controversial case to test to solve it later.

### CODE REVIEW

**Comment by kamilsk** [comment]
works for me https://github.com/kamilsk/lift/commit/9afe77a85b7866a0522d0dd4c3d85b2e51ce2efc#diff-d6ad193953b17054f326552f4e2136be

**Comment by pelletier** [comment]
Thank you very much for the patch!

Not sure I understand, how is the second test controversial?

**Comment by kamilsk** [comment]
> Not sure I understand, how is the second test controversial?

https://github.com/pelletier/go-toml/blob/dba45d427ff48cfb9bcf633db3a8e43b7364e261/marshal.go#L552-L557

The current logic tries to pick up different keys. This may cause an error

https://github.com/pelletier/go-toml/blob/dba45d427ff48cfb9bcf633db3a8e43b7364e261/marshal.go#L566-L569

in the following scenario 

https://github.com/pelletier/go-toml/blob/dba45d427ff48cfb9bcf633db3a8e43b7364e261/marshal_test.go#L1445-L1454

For example, this is `json` behavior: https://play.golang.org/p/Y2-IqgIEUI8. I don't know how to fix it and don't break backwards compatibility.

**Comment by pelletier** [comment]
Ah right. Yes, that's not ideal, but I'm happy this patch is in to at least provide partial support for people who need it. I am [rewriting the unmarshal code](https://github.com/pelletier/go-toml/tree/unmarshal-rewrite) from the ground up to behave like JSON, including for this use-case. In the meantime, this is a good-enough stopgap.

**Pull request merged**
