### PR TITLE
🔒  Fuzzing setup and fixes

### PR DESCRIPTION
**Pull request by pelletier**
Finding and fixing bugs in the encoder with Go 1.18 fuzzing.

### CODE REVIEW

**Comment by moorereason** [comment]
Why do you not allow fuzzing on Windows?

**Comment by pelletier** [comment]
@moorereason the Go fuzz runner seems to be failing for some internal reason on windows. Figured I’d block it until I can figure out what’s wrong there.

**Comment by moorereason** [comment]
I tested the Windows fuzzing piece and opened golang/go#52268.

The work-around is some form of these Git settings:
```
git clone https://github.com/pelletier/go-toml.git --config core.autocrlf=false --config core.eol=lf
```

**Comment by moorereason** [comment]
Also, please keep this `fixes` branch around for a while since I reference it in the upstream issue.

**Comment by pelletier** [comment]
Cool! Thank you for looking into this. I've added branch protection on this one to make sure it does not go away. Creating a new PR to get those fixes in. I'll try to play with `.gitattributes` to see if this issue can be worked-around.

**Comment by pelletier** [comment]
Confirmed that adding an entry to `.gitattributes` works: https://github.com/pelletier/go-toml/pull/755/commits/bb2fabec9cbb30fd626640d4c5eb2568ba0aae7c.

**Comment by pelletier** [comment]
@moorereason since https://github.com/golang/go/issues/52268 has been closed, mind if I close this one and delete the branch too?

**Comment by moorereason** [comment]
Agreed

**Pull request closed without merging**
